version: '3.8'

services:
  backend:
    build: .
    container_name: backend-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
