- name: Deploy to EC2
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USERNAME }}
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |
      aws ecr get-login-password --region eu-north-1 | sudo docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}
      sudo docker pull ${{ steps.login-ecr.outputs.registry }}/my-backend-repos:latest
      sudo docker stop my-backend-service || true
      sudo docker rm my-backend-service || true
      sudo docker run -d --name my-backend-service -p 3000:3000 ${{ steps.login-ecr.outputs.registry }}/my-backend-repos:latest
      sudo docker system prune -f
      sudo docker ps -a
